export const BUGS = [
  // Original 5 — also used as potion ingredients
  {
    id: 'glowgrub',
    name: 'Glowgrub',
    rarity: 'common',
    color: '#d8e868',
    lore: 'Found under damp leaves near the base of garden herbs. Bioluminescent larvae. Alchemists keep jars of them for light.',
  },
  {
    id: 'moonmite',
    name: 'Moonmite',
    rarity: 'uncommon',
    color: '#c8c8f0',
    lore: 'Microscopic in daylight, somehow visible at night. Collected by pressing cloth against moonlit leaves.',
  },
  {
    id: 'ashcrawler',
    name: 'Ashcrawler',
    rarity: 'uncommon',
    color: '#989898',
    lore: 'Lives in the dry crust around ashroot. Its shell is fire-resistant. Grinding it produces a fine grey powder.',
  },
  {
    id: 'voidweevil',
    name: 'Voidweevil',
    rarity: 'rare',
    color: '#5848a8',
    lore: 'Bores into voidleaf stems. Nobody planted them there. Nobody knows where they came from.',
  },
  {
    id: 'cinderfly',
    name: 'Cinderfly',
    rarity: 'epic',
    color: '#e07b39',
    lore: 'Wings that shed embers when disturbed. Found once in forty harvests, if that. Worth catching carefully.',
  },

  // 20 new collectible-only bugs
  {
    id: 'thornweaver',
    name: 'Thornweaver',
    rarity: 'common',
    color: '#8ca86e',
    lore: 'Weaves silk tunnels between plant stems to funnel moisture and trap pollen. Old gardeners leave patches undisturbed and claim the soil improves for it.',
  },
  {
    id: 'dustmoth',
    name: 'Dustmoth',
    rarity: 'common',
    color: '#c8b890',
    lore: 'Wings release a silver-grey powder on contact with anything. Alchemists have attempted to replicate the compound for thirty years without success.',
  },
  {
    id: 'ironback',
    name: 'Ironback',
    rarity: 'common',
    color: '#787870',
    lore: 'Shell hard enough to blunt pruning shears. Rolls into a perfect sphere when startled, then waits without impatience until the threat has passed.',
  },
  {
    id: 'verdantick',
    name: 'Verdantick',
    rarity: 'common',
    color: '#78a858',
    lore: 'Feeds on dilute herb sap without harming the host. Old herbalists considered them a good omen. Newer herbalists agree but will not say so.',
  },
  {
    id: 'rootspinner',
    name: 'Rootspinner',
    rarity: 'common',
    color: '#a8a870',
    lore: 'Burrows through soil in spiraling paths, aerating the ground around plant roots. Gardens with a healthy rootspinner population are noticeably more productive.',
  },
  {
    id: 'sporecrawler',
    name: 'Sporecrawler',
    rarity: 'uncommon',
    color: '#c890c0',
    lore: 'Found exclusively on mushroom caps, where it feeds, breeds, and eventually dies without ever touching soil. Cannot survive without its host for more than a day.',
  },
  {
    id: 'mistveil',
    name: 'Mistveil',
    rarity: 'uncommon',
    color: '#b8d8e8',
    lore: 'Wings scatter into a haze the moment they sense breath on the body. Collectors use long tongs and learn not to exhale sharply.',
  },
  {
    id: 'tangleworm',
    name: 'Tangleworm',
    rarity: 'uncommon',
    color: '#a0c870',
    lore: 'Wraps itself around plant roots in mathematically precise spirals. Untangling one without it knotting tighter has become an unofficial test of patience among apprentice gardeners.',
  },
  {
    id: 'glassbeetle',
    name: 'Glassbeetle',
    rarity: 'uncommon',
    color: '#d8f0e8',
    lore: 'Carapace is entirely transparent, revealing all its organs in operation. Scholars find it instructive. Most people find it deeply unsettling and prefer not to look.',
  },
  {
    id: 'stonewalker',
    name: 'Stonewalker',
    rarity: 'uncommon',
    color: '#888880',
    lore: 'Moves at approximately one centimeter per hour. Feeds on mineral dust and is rumored to live for decades. Several in the valley may be older than anyone currently living.',
  },
  {
    id: 'deepcrawler',
    name: 'Deepcrawler',
    rarity: 'uncommon',
    color: '#505060',
    lore: 'Emerges from the lowest soil layer only during heavy rain. Surfaces with visible reluctance and descends again the moment conditions permit. The surface disagrees with it.',
  },
  {
    id: 'embermoth',
    name: 'Embermoth',
    rarity: 'rare',
    color: '#e09858',
    lore: 'Congregates near heat sources with puzzling preference. Its wings resist temperatures that would destroy most organic matter. Alchemists remain annoyed that no one can explain why.',
  },
  {
    id: 'duskwing',
    name: 'Duskwing',
    rarity: 'rare',
    color: '#908098',
    lore: 'Visible only during the transitional minutes of dusk and dawn. Something about the quality of those particular lights draws it out. It ignores every other hour of the day.',
  },
  {
    id: 'prismbeetle',
    name: 'Prismbeetle',
    rarity: 'rare',
    color: '#a8d8f0',
    lore: 'Scales refract light into full spectra. When enough gather in one place the effect is disorienting. Opticians in the capital pay generously for living specimens, if kept calm.',
  },
  {
    id: 'rootling',
    name: 'Rootling',
    rarity: 'rare',
    color: '#a87848',
    lore: 'When threatened, its body changes texture and colour to match woody stems precisely. It then remains stationary for as long as it takes. It is very patient.',
  },
  {
    id: 'shimmerfly',
    name: 'Shimmerfly',
    rarity: 'rare',
    color: '#d0b8f0',
    lore: 'Wings refract moonlight. Has caused seven documented incidents involving local residents mistaking small swarms for ghosts. Serevane finds this delightful.',
  },
  {
    id: 'crystalmite',
    name: 'Crystalmite',
    rarity: 'rare',
    color: '#b8d0f0',
    lore: 'Deposits mineral crystals on its carapace throughout its life. Eldest specimens, barely able to move under the accumulated weight, are considered the rarest finds in any collection.',
  },
  {
    id: 'nightshroud',
    name: 'Nightshroud',
    rarity: 'epic',
    color: '#2a2838',
    lore: 'Absorbs ambient light in its immediate vicinity, creating a perceptible pocket of shadow even in bright daylight. Serevane keeps several. She does not explain why.',
  },
  {
    id: 'solarweevil',
    name: 'Solarweevil',
    rarity: 'epic',
    color: '#f0d840',
    lore: 'Active only in direct sunlight. Stores heat in specialized organs and metabolizes it slowly through winter. In summer it is vivid and almost difficult to look at directly.',
  },
  {
    id: 'voidwing',
    name: 'Voidwing',
    rarity: 'epic',
    color: '#6848a8',
    lore: 'A distant aerial cousin of the voidweevil, sharing its unaccountable origin. Found in locations that defy prediction: deep underground, inside sealed vessels, never twice in the same place.',
  },
]

export const BUG_MAP = Object.fromEntries(BUGS.map(b => [b.id, b]))
