// Original 5 bugs — also used as potion ingredients
export const BUGS = [
  // Original 5 — also used as potion ingredients
  {
    id: 'glowgrub',
    name: 'Glowgrub',
    rarity: 'common',
    color: '#d8e868',
    lore: 'Found under damp leaves near the base of garden herbs. Bioluminescent larvae. Alchemists keep jars of them for light.',
  },
  {
    id: 'moonmite',
    name: 'Moonmite',
    rarity: 'uncommon',
    color: '#c8c8f0',
    lore: 'Microscopic in daylight, somehow visible at night. Collected by pressing cloth against moonlit leaves.',
  },
  {
    id: 'ashcrawler',
    name: 'Ashcrawler',
    rarity: 'uncommon',
    color: '#989898',
    lore: 'Lives in the dry crust around ashroot. Its shell is fire-resistant. Grinding it produces a fine grey powder.',
  },
  {
    id: 'voidweevil',
    name: 'Voidweevil',
    rarity: 'rare',
    color: '#5848a8',
    lore: 'Bores into voidleaf stems. Nobody planted them there. Nobody knows where they came from.',
  },
  {
    id: 'cinderfly',
    name: 'Cinderfly',
    rarity: 'epic',
    color: '#e07b39',
    lore: 'Wings that shed embers when disturbed. Found once in forty harvests, if that. Worth catching carefully.',
  },

  // 20 new collectible-only bugs
  {
    id: 'thornweaver',
    name: 'Thornweaver',
    rarity: 'common',
    color: '#8ca86e',
    lore: 'Weaves silk tunnels between plant stems to funnel moisture and trap pollen. Old gardeners leave patches undisturbed and claim the soil improves for it.',
  },
  {
    id: 'dustmoth',
    name: 'Dustmoth',
    rarity: 'common',
    color: '#c8b890',
    lore: 'Wings release a silver-grey powder on contact with anything. Alchemists have attempted to replicate the compound for thirty years without success.',
  },
  {
    id: 'ironback',
    name: 'Ironback',
    rarity: 'common',
    color: '#787870',
    lore: 'Shell hard enough to blunt pruning shears. Rolls into a perfect sphere when startled, then waits without impatience until the threat has passed.',
  },
  {
    id: 'verdantick',
    name: 'Verdantick',
    rarity: 'common',
    color: '#78a858',
    lore: 'Feeds on dilute herb sap without harming the host. Old herbalists considered them a good omen. Newer herbalists agree but will not say so.',
  },
  {
    id: 'rootspinner',
    name: 'Rootspinner',
    rarity: 'common',
    color: '#a8a870',
    lore: 'Burrows through soil in spiraling paths, aerating the ground around plant roots. Gardens with a healthy rootspinner population are noticeably more productive.',
  },
  {
    id: 'sporecrawler',
    name: 'Sporecrawler',
    rarity: 'uncommon',
    color: '#c890c0',
    lore: 'Found exclusively on mushroom caps, where it feeds, breeds, and eventually dies without ever touching soil. Cannot survive without its host for more than a day.',
  },
  {
    id: 'mistveil',
    name: 'Mistveil',
    rarity: 'uncommon',
    color: '#b8d8e8',
    lore: 'Wings scatter into a haze the moment they sense breath on the body. Collectors use long tongs and learn not to exhale sharply.',
  },
  {
    id: 'tangleworm',
    name: 'Tangleworm',
    rarity: 'uncommon',
    color: '#a0c870',
    lore: 'Wraps itself around plant roots in mathematically precise spirals. Untangling one without it knotting tighter has become an unofficial test of patience among apprentice gardeners.',
  },
  {
    id: 'glassbeetle',
    name: 'Glassbeetle',
    rarity: 'uncommon',
    color: '#d8f0e8',
    lore: 'Carapace is entirely transparent, revealing all its organs in operation. Scholars find it instructive. Most people find it deeply unsettling and prefer not to look.',
  },
  {
    id: 'stonewalker',
    name: 'Stonewalker',
    rarity: 'uncommon',
    color: '#888880',
    lore: 'Moves at approximately one centimeter per hour. Feeds on mineral dust and is rumored to live for decades. Several in the valley may be older than anyone currently living.',
  },
  {
    id: 'deepcrawler',
    name: 'Deepcrawler',
    rarity: 'uncommon',
    color: '#505060',
    lore: 'Emerges from the lowest soil layer only during heavy rain. Surfaces with visible reluctance and descends again the moment conditions permit. The surface disagrees with it.',
  },
  {
    id: 'embermoth',
    name: 'Embermoth',
    rarity: 'rare',
    color: '#e09858',
    lore: 'Congregates near heat sources with puzzling preference. Its wings resist temperatures that would destroy most organic matter. Alchemists remain annoyed that no one can explain why.',
  },
  {
    id: 'duskwing',
    name: 'Duskwing',
    rarity: 'rare',
    color: '#908098',
    lore: 'Visible only during the transitional minutes of dusk and dawn. Something about the quality of those particular lights draws it out. It ignores every other hour of the day.',
  },
  {
    id: 'prismbeetle',
    name: 'Prismbeetle',
    rarity: 'rare',
    color: '#a8d8f0',
    lore: 'Scales refract light into full spectra. When enough gather in one place the effect is disorienting. Opticians in the capital pay generously for living specimens, if kept calm.',
  },
  {
    id: 'rootling',
    name: 'Rootling',
    rarity: 'rare',
    color: '#a87848',
    lore: 'When threatened, its body changes texture and colour to match woody stems precisely. It then remains stationary for as long as it takes. It is very patient.',
  },
  {
    id: 'shimmerfly',
    name: 'Shimmerfly',
    rarity: 'rare',
    color: '#d0b8f0',
    lore: 'Wings refract moonlight. Has caused seven documented incidents involving local residents mistaking small swarms for ghosts. Serevane finds this delightful.',
  },
  {
    id: 'crystalmite',
    name: 'Crystalmite',
    rarity: 'rare',
    color: '#b8d0f0',
    lore: 'Deposits mineral crystals on its carapace throughout its life. Eldest specimens, barely able to move under the accumulated weight, are considered the rarest finds in any collection.',
  },
  {
    id: 'nightshroud',
    name: 'Nightshroud',
    rarity: 'epic',
    color: '#2a2838',
    lore: 'Absorbs ambient light in its immediate vicinity, creating a perceptible pocket of shadow even in bright daylight. Serevane keeps several. She does not explain why.',
  },
  {
    id: 'solarweevil',
    name: 'Solarweevil',
    rarity: 'epic',
    color: '#f0d840',
    lore: 'Active only in direct sunlight. Stores heat in specialized organs and metabolizes it slowly through winter. In summer it is vivid and almost difficult to look at directly.',
  },
  {
    id: 'voidwing',
    name: 'Voidwing',
    rarity: 'epic',
    color: '#6848a8',
    lore: 'A distant aerial cousin of the voidweevil, sharing its unaccountable origin. Found in locations that defy prediction: deep underground, inside sealed vessels, never twice in the same place.',
  },
]

// 20 collectible-only bugs — found via the 1% collectible roll, not the regular bug drop
export const COLLECTIBLE_BUGS = [
  {
    id: 'crystalwing',
    name: 'Crystalwing',
    rarity: 'rare',
    color: '#c8e8f8',
    lore: 'Wings composed of chitin so thin they refract light into tiny rainbows. Found only when the sun hits the garden at exactly the right angle.',
  },
  {
    id: 'rootborer',
    name: 'Rootborer',
    rarity: 'common',
    color: '#8a6040',
    lore: 'A stout beetle that tunnels through root systems without damaging them. It leaves a scent that wards off parasitic fungi.',
  },
  {
    id: 'inkblot_moth',
    name: 'Inkblot Moth',
    rarity: 'uncommon',
    color: '#303048',
    lore: 'The wing pattern changes subtly between individuals, but each resembles a spilled ink drop. Cartographers once used them for manuscript ink.',
  },
  {
    id: 'frostling',
    name: 'Frostling',
    rarity: 'uncommon',
    color: '#c8e0f0',
    lore: 'A pale mite found clustered around coldvine roots. Despite its name and habitat, it is not cold to the touch.',
  },
  {
    id: 'miremite',
    name: 'Miremite',
    rarity: 'common',
    color: '#6a7848',
    lore: 'Breeds in standing water between garden rows. Harmless in small numbers. In large numbers, still harmless, but unsettling to observe.',
  },
  {
    id: 'dewdancer',
    name: 'Dewdancer',
    rarity: 'common',
    color: '#88c8a8',
    lore: 'Skims the surface of dew on broad leaves. Its legs are coated in a wax-like substance that prevents surface tension from releasing.',
  },
  {
    id: 'speckleshell',
    name: 'Speckleshell',
    rarity: 'common',
    color: '#b8a888',
    lore: 'The spots on its carapace are unique to each individual, like fingerprints. Whether this has practical significance is unknown.',
  },
  {
    id: 'ghostfly',
    name: 'Ghostfly',
    rarity: 'rare',
    color: '#d8d8e8',
    lore: 'The wing membrane is nearly invisible in direct light. In shadow it becomes a faint shimmer. Many people have swatted at air for this reason.',
  },
  {
    id: 'bloodthorn_beetle',
    name: 'Bloodthorn Beetle',
    rarity: 'uncommon',
    color: '#a83838',
    lore: 'The red tips of its mandibles are stained from feeding exclusively on firethorn roots. Removing the stain has proven impossible.',
  },
  {
    id: 'thornscuttler',
    name: 'Thornscuttler',
    rarity: 'common',
    color: '#788048',
    lore: 'Moves in sharp, angular bursts. Not faster than other beetles — just less predictable. Researchers have described the movement as profoundly useless to model.',
  },
  {
    id: 'ambermite',
    name: 'Ambermite',
    rarity: 'uncommon',
    color: '#d8a840',
    lore: 'Found exclusively near dried tree sap. It does not consume the amber but appears compelled to remain near it indefinitely.',
  },
  {
    id: 'wraithworm',
    name: 'Wraithworm',
    rarity: 'rare',
    color: '#c8c8d8',
    lore: 'Translucent to the point that no digestive system is visible. It appears to eat. What happens after is the outstanding question.',
  },
  {
    id: 'emberbeetle',
    name: 'Emberbeetle',
    rarity: 'uncommon',
    color: '#d87040',
    lore: 'Seeks out heat sources with unexpected precision. Found inside forge bellows once, inexplicably unharmed.',
  },
  {
    id: 'lumimoth',
    name: 'Lumimoth',
    rarity: 'rare',
    color: '#e8e0a0',
    lore: 'The wing scales produce a soft, steady light when the moth is still. No relation to the cinderfly. One produces light, the other fire.',
  },
  {
    id: 'saltcrawler',
    name: 'Saltcrawler',
    rarity: 'common',
    color: '#c8b8a0',
    lore: 'Attracted to salt deposits and dried preservation mixtures. Often found near herb-drying operations, where it does nothing harmful and is simply present.',
  },
  {
    id: 'duskling',
    name: 'Duskling',
    rarity: 'uncommon',
    color: '#887898',
    lore: 'Active for approximately forty minutes at dusk, then dormant until the following evening. During this window it moves with no apparent purpose.',
  },
  {
    id: 'ridgewalker',
    name: 'Ridgewalker',
    rarity: 'common',
    color: '#989870',
    lore: 'Found on elevated garden borders and stone walls. Prefers the high ground entirely for temperature, not defense.',
  },
  {
    id: 'hollowtick',
    name: 'Hollowtick',
    rarity: 'rare',
    color: '#a09080',
    lore: 'Named for the hollow clicking sound it produces in clusters. Single specimens make no sound. The mechanism is not understood.',
  },
  {
    id: 'spectermite',
    name: 'Spectermite',
    rarity: 'epic',
    color: '#a8a8c0',
    lore: 'Appears partially phased. Standard containment does not hold it. Five collection attempts are documented in the codex. All unsuccessful.',
  },
  {
    id: 'veilwing',
    name: 'Veilwing',
    rarity: 'epic',
    color: '#d8c0f0',
    lore: 'Leaves a shimmering trail in the air for approximately three seconds after passing. Two analyses have been conducted. Both results were inconclusive.',
  },
]

export const ALL_BUGS = [...BUGS, ...COLLECTIBLE_BUGS]
export const BUG_MAP  = Object.fromEntries(ALL_BUGS.map(b => [b.id, b]))
