// All potions. brewTime in seconds. cauldronTier: 1-4.
// Tier 1 = single ingredient type only (apprentice brews)
// Tier 2+ = multi-ingredient recipes
export const POTIONS = [
  // ── TIER 1 — Single-ingredient brews ──
  {
    id: 'silverleaf_salve',
    name: 'Silverleaf Salve',
    ingredients: { silverleaf: 2 },
    brewTime: 120,
    cauldronTier: 1,
    xpReward: 8,
    sellValue: 10,
    color: '#c0d0e0',
    lore: 'The simplest remedy in any herbalist\'s kit. Every apprentice starts here.',
  },
  {
    id: 'dewcap_draft',
    name: 'Dewcap Draft',
    ingredients: { dewcap: 3 },
    brewTime: 150,
    cauldronTier: 1,
    xpReward: 10,
    sellValue: 12,
    color: '#7ab8a0',
    lore: 'Three caps steeped until the liquid turns green. Refreshing, if you don\'t smell it first.',
  },
  {
    id: 'ironwort_tonic',
    name: 'Ironwort Tonic',
    ingredients: { ironwort: 2 },
    brewTime: 180,
    cauldronTier: 1,
    xpReward: 12,
    sellValue: 14,
    color: '#9a9878',
    lore: 'Ground stems suspended in water. Laborers swear by it. Tastes like it.',
  },
  {
    id: 'whisper_tea',
    name: 'Whispergrass Tea',
    ingredients: { whispergrass: 4 },
    brewTime: 100,
    cauldronTier: 1,
    xpReward: 7,
    sellValue: 9,
    color: '#a8c888',
    lore: 'Four stalks, no more. The meadow folk have been brewing this for three hundred years.',
  },

  // ── TIER 2 — Two to three ingredients ──
  {
    id: 'minor_healing',
    name: 'Minor Healing Potion',
    ingredients: { silverleaf: 2, dewcap: 1 },
    brewTime: 300,
    cauldronTier: 2,
    xpReward: 20,
    sellValue: 22,
    color: '#c84848',
    lore: 'Seals small wounds. Tastes of copper and regret.',
  },
  {
    id: 'stamina',
    name: 'Stamina Brew',
    ingredients: { whispergrass: 3, ironwort: 2 },
    brewTime: 420,
    cauldronTier: 2,
    xpReward: 25,
    sellValue: 32,
    color: '#c9a227',
    lore: 'Mira Dunvale orders these by the crate. Her porters haven\'t complained in years.',
  },
  {
    id: 'clarity',
    name: 'Potion of Clarity',
    ingredients: { spiritmint: 2, whispergrass: 2, dewcap: 1 },
    brewTime: 480,
    cauldronTier: 2,
    xpReward: 30,
    sellValue: 40,
    color: '#88ccff',
    lore: 'Voss the Scholar requires three per week. His correspondence is formidable.',
  },
  {
    id: 'healing',
    name: 'Healing Potion',
    ingredients: { silverleaf: 3, dewcap: 2, moonbloom: 1 },
    brewTime: 600,
    cauldronTier: 2,
    xpReward: 35,
    sellValue: 50,
    color: '#e05050',
    lore: 'Mends broken ribs, fractured spirits. Standard issue for adventurers.',
  },
  {
    id: 'shadow_oil',
    name: 'Shadow Oil',
    ingredients: { ashroot: 3, shadowfung: 1 },
    brewTime: 720,
    cauldronTier: 2,
    xpReward: 40,
    sellValue: 65,
    color: '#484858',
    lore: 'Applied to leather, it dulls reflected light. Common request from those who value discretion.',
  },
  {
    id: 'moonbrew',
    name: 'Moonbrew',
    ingredients: { moonbloom: 2, moonshroom: 1, dewshroom: 1 },
    brewTime: 900,
    cauldronTier: 2,
    xpReward: 55,
    sellValue: 90,
    color: '#c8c8f0',
    lore: 'Effects vary by lunar phase. Serevane insists this is a feature.',
  },
  {
    id: 'fire_tonic',
    name: 'Fire Tonic',
    ingredients: { firethorn: 2, embercrown: 1, ashroot: 1 },
    brewTime: 840,
    cauldronTier: 2,
    xpReward: 45,
    sellValue: 72,
    color: '#e08040',
    lore: 'Warms from the inside out. Commander Thresh issues them before winter campaigns.',
  },
  {
    id: 'cold_extract',
    name: 'Cold Extract',
    ingredients: { coldvine: 2, dewcap: 2, spiritmint: 1 },
    brewTime: 1080,
    cauldronTier: 2,
    xpReward: 60,
    sellValue: 100,
    color: '#88b8d8',
    lore: 'Preserves. Both foods and the memories of those who drink it, if the stories are true.',
  },
  {
    id: 'verdant_draught',
    name: 'Verdant Draught',
    ingredients: { verdant_moss: 3, gloomcap: 2, rotmoss: 1 },
    brewTime: 960,
    cauldronTier: 2,
    xpReward: 50,
    sellValue: 80,
    color: '#5a9e6f',
    lore: 'Olwen the Herbalist drinks one each morning. She is eighty-three and hikes daily.',
  },
  {
    id: 'dusk_elixir',
    name: 'Dusk Elixir',
    ingredients: { duskpetal: 3, spectral_cap: 1, moonbloom: 1 },
    brewTime: 1200,
    cauldronTier: 2,
    xpReward: 65,
    sellValue: 115,
    color: '#c888a8',
    lore: 'The petals dissolve in the bottle within an hour. Must be drunk quickly.',
  },

  // ── TIER 3 ──
  {
    id: 'goldvein_tonic',
    name: 'Goldvein Tonic',
    ingredients: { goldthread: 2, embervine: 1, brightfungus: 2 },
    brewTime: 2400,
    cauldronTier: 3,
    xpReward: 110,
    sellValue: 220,
    color: '#d4a830',
    lore: 'Aldric Fenn uses it before negotiations. Enhances something he calls "cartographic intuition."',
  },
  {
    id: 'void_tincture',
    name: 'Void Tincture',
    ingredients: { voidleaf: 2, voidweevil: 1, nightshade_pale: 1 },
    brewTime: 3600,
    cauldronTier: 3,
    xpReward: 150,
    sellValue: 310,
    color: '#5848a8',
    lore: 'Three drops. Never four. The bottle itself seems reluctant to pour.',
  },
  {
    id: 'ember_salve',
    name: 'Ember Salve',
    ingredients: { embervine: 2, cinderfly: 1, firethorn: 1, ashcrawler: 1 },
    brewTime: 4200,
    cauldronTier: 3,
    xpReward: 170,
    sellValue: 360,
    color: '#e07b39',
    lore: 'Applied to smith\'s hands, it prevents blistering through twelve-hour forge sessions.',
  },
  {
    id: 'moonmite_serum',
    name: 'Moonmite Serum',
    ingredients: { moonmite: 2, moonshroom: 2, spectral_cap: 1 },
    brewTime: 3900,
    cauldronTier: 3,
    xpReward: 160,
    sellValue: 330,
    color: '#d8d8ff',
    lore: 'Serevane has the exclusive contract. She has not disclosed what it does.',
  },

  // ── TIER 4 ──
  {
    id: 'grand_elixir',
    name: 'Grand Restoration Elixir',
    ingredients: { embervine: 2, voidleaf: 1, goldthread: 2, moonshroom: 1 },
    brewTime: 6000,
    cauldronTier: 4,
    xpReward: 250,
    sellValue: 600,
    color: '#f0c842',
    lore: 'The most complete healing compound known. Aldric carries two and has never used them.',
  },
  {
    id: 'void_dissolution',
    name: 'Void Dissolution',
    ingredients: { voidmold: 2, voidweevil: 2, voidleaf: 2, cinderfly: 1 },
    brewTime: 7200,
    cauldronTier: 4,
    xpReward: 300,
    sellValue: 750,
    color: '#282848',
    lore: 'Dissolves the boundary between what is and what was. Commander Thresh has standing orders for all available stock.',
  },
  {
    id: 'stellar_brew',
    name: 'Stellar Brew',
    ingredients: { embervine: 1, goldthread: 2, moonmite: 2, glowgrub: 2 },
    brewTime: 5400,
    cauldronTier: 4,
    xpReward: 220,
    sellValue: 540,
    color: '#88aaff',
    lore: 'Smells of cold nights and open sky. The glowgrubs are primarily for luminescence. Mostly.',
  },
]

export const POTION_MAP = Object.fromEntries(POTIONS.map(p => [p.id, p]))
